### PR TITLE
[replay] generate network visualization replay

### PR DESCRIPTION
**Pull request by simonlingoogle**
The replay filename is `otns_<PORT_OFFSET>.replay`
The replay output is pure text. 

**The implementation takes advantage of the gRPC service which has already constructed protobuf message for each visualization event by marshaling event protobuf messsages to strings.**

Example replay file content. 
```prototext
timestamp:28536 event:{set_speed:{speed:1}}
timestamp:28568 event:{set_network_info:{commit:"master"}}
timestamp:1894844 event:{add_node:{node_id:1 x:194 y:790 radio_range:160}}
timestamp:1900008 event:{on_ext_addr_change:{node_id:1 ext_addr:9426503932554449306}}
timestamp:1900575 event:{set_node_rloc16:{node_id:1 rloc16:65534}}
timestamp:1908102 event:{set_node_rloc16:{node_id:1 rloc16:65534}}
timestamp:1908244 event:{set_node_role:{node_id:1 role:OT_DEVICE_ROLE_DETACHED}}
timestamp:2353328 event:{send:{src_id:1 dst_id:-1 mv_info:{channel:11 frame_control:55361 seq:188 dst_addr_short:65535}}}
timestamp:2915263 event:{advance_time:{ts:1000000 speed:0.9996850991937539}}
timestamp:3113440 event:{send:{src_id:1 dst_id:-1 mv_info:{channel:11 frame_control:55361 seq:189 dst_addr_short:65535}}}
timestamp:3465867 event:{add_node:{node_id:2 x:242 y:807 radio_range:160}}
timestamp:3473095 event:{on_ext_addr_change:{node_id:2 ext_addr:1021973091034100516}}
timestamp:3473244 event:{set_node_rloc16:{node_id:2 rloc16:65534}}
timestamp:3477150 event:{set_node_rloc16:{node_id:2 rloc16:65534}}
timestamp:3477633 event:{set_node_role:{node_id:2 role:OT_DEVICE_ROLE_DETACHED}}
timestamp:3850769 event:{send:{src_id:2 dst_id:-1 mv_info:{channel:11 frame_control:55361 seq:215 dst_addr_short:65535}}}
timestamp:3923156 event:{advance_time:{ts:2000000 speed:0.9992984924582943}}
timestamp:4372915 event:{set_node_rloc16:{node_id:1 rloc16:14336}}
timestamp:4375407 event:{set_node_role:{node_id:1 role:OT_DEVICE_ROLE_LEADER}}
timestamp:4375495 event:{set_node_partition_id:{node_id:1 partition_id:762265344}}
timestamp:4376564 event:{send:{src_id:1 dst_id:-1 mv_info:{channel:11 frame_control:55361 seq:190 dst_addr_short:65535}}}
timestamp:4614281 event:{send:{src_id:2 dst_id:-1 mv_info:{channel:11 frame_control:55361 seq:216 dst_addr_short:65535}}}
timestamp:4686521 event:{send:{src_id:1 dst_id:2 mv_info:{channel:11 frame_control:56417 seq:191 dst_addr_extended:1021973091034100516}}}
timestamp:4934641 event:{advance_time:{ts:3000000 speed:0.9998680174217003}}
timestamp:5093500 event:{send:{src_id:1 dst_id:-1 mv_info:{channel:11 frame_control:55361 seq:192 dst_addr_short:65535}}}
```

Other replay utilities (e.g. replay playing) to be implemented.

### CODE REVIEW

**Comment by wgtdkp** [comment]
How could this feature be used?

**Comment by simonlingoogle** [comment]
> How could this feature be used?

Good question. 

I think the replay file can be used in many ways:
- Replays can be played as demos.
- Replays (together with PCAP) can be used for debugging network issues.
- Replays can be used as an extra log file (since it's of text format)

If you are asking about implementation. The replay files can be played by an `OTNS Replay Player` (to be developed). 

Thoughts? @wgtdkp

**Comment by wgtdkp** [comment]
@simonlingoogle So this file actually remembers all events in a test and we can reproduce a failure by redo those events, right?

**Comment by simonlingoogle** [comment]
> events in a test and we can reproduce a failure by redo those events

Yes, but only visualization related events. For example, you can see nodes become Routers or nodes RLOC16 changes. 
It basically exactly the same thing you saw when running the simulation on OTNS.

**Pull request merged**
