### PR TITLE
[doc] auto-gen Python doc using Sphinx

### PR DESCRIPTION
**Pull request by simonlingoogle**
This PR adds required files for generating python docs by [Sphinx 3.x](https://www.sphinx-doc.org/en/3.x/usage/quickstart.html).

### CODE REVIEW

**Comment by simonlingoogle** [comment]
Where should we serve these docs? Should we add the docs to openthread.io? @jwhui @Vyrastas

**Comment by Vyrastas** [comment]
I haven't used Sphinx before and don't know if there's support to convert its output to DevSite-friendly pages (for openthread.io).  So for the moment we wouldn't put them there.

**Comment by simonlingoogle** [comment]
Seems [pydoc3](https://docs.python.org/3/library/pydoc.html) can serve documents well. 
Normally users can just use `pydoc3 -b` to open the documents and navigate to the `otns` module. 

I will later close this PR and create another one to better support pydoc3.

**Comment by simonlingoogle** [comment]
Close in favor of #10

**Pull request closed without merging**
