### PR TITLE
Resolve CI issues and misc enhancements

### PR DESCRIPTION
**Pull request by simonlingoogle**
Highlight enhancements:

- Support golang 1.18
- Remove supporting for `VIRTUAL_TIME_UART=OFF`
- Build openthread with `script/test build-openthread`
- Make sure `pack-web` is executed consistently

### CODE REVIEW

**Comment by simonlingoogle** [comment]
@EskoDijk Currently GitHub CI is failing due to various issues. 

This PR resolves all CI issues with other small enhancements.

**Comment by EskoDijk** [comment]
@simonlingoogle I tried out the new CI scripts and it works. Just a note that one stress test failed:
#### ML-EID Connectivity Test **Failed**: Max Delay (4800s)> 3600s _(08/31 10:09:10 ~ 08/31 10:27:17)_

One thing that was surprising is that two different versions of the "protobuf" library are mentioned. (Maybe needed by different components?) (One of the two is flagged as "deprecated" but for our purposes it should work ok nevertheless.)

I see that now Go 1.17+ is mentioned as a requirement, however I was using Go 1.13 on Ubuntu 20.04 so far which seemd to work ok. Is there a reason to increase the minimum, e.g. to make supporting different Go versions easier? (If CI only tests on Go 1.18 I can imagine that 1.13 is maybe not supported just for that reason - it's not being tested.)

As to the rest of changes, I'm not so familiar with these configurations so cannot comment much.

**Review by EskoDijk — APPROVED** [review]
see prior comments; overall looks okay & CI works again with this PR

**Comment by simonlingoogle** [comment]
> @simonlingoogle I tried out the new CI scripts and it works. 

Thanks for confirmation. 

> Just a note that one stress test failed:
> 
> #### ML-EID Connectivity Test **Failed**: Max Delay (4800s)> 3600s _(08/31 10:09:10 ~ 08/31 10:27:17)_

It's a known issue. 

> One thing that was surprising is that two different versions of the "protobuf" library are mentioned. (Maybe needed by different components?) (One of the two is flagged as "deprecated" but for our purposes it should work ok nevertheless.)

We are using `google.golang.org/protobuf` which I believe is correct.

However, the auto-generated code (i.e. visualize_grpc.pb.go) is still using `github.com/golang/protobuf`. I think the issue can be resolved by upgrading protoc_gen_go (TODO). 

> I see that now Go 1.17+ is mentioned as a requirement, however I was using Go 1.13 on Ubuntu 20.04 so far which seemd to work ok. Is there a reason to increase the minimum, e.g. to make supporting different Go versions easier? (If CI only tests on Go 1.18 I can imagine that 1.13 is maybe not supported just for that reason - it's not being tested.)

IIRC, Go 1.13 failed in some CI checks. It's still possible to build otns in Go 1.13, but we want to reduce the maintenance efforts. Note that Go 1.17 was released more than a year ago.

**Review by jwhui — APPROVED** [review]

**Pull request merged**
