### PR TITLE
[visualization] adjust with network info

### PR DESCRIPTION
**Pull request by simonlingoogle**
This PR adds a new visualization event and command: `netinfo`

The `netinfo` event contains:

- Version: OpenThread version (for displaying)
- Commit: OpenThread Commit (for URL navigating)
- Real: if the network is using real devices

New CLI command is added for configuring netinfo. 

OTNS-Web will adjust visualization and management according to `netinfo`:

- Show version and tag at the top left of page
- Hide action bar buttons when `Real`

### CODE REVIEW

**Comment by simonlingoogle** [comment]
> Shall it also hide the pause icon on speed button in real mode?

It also used to display the current replay speed. 
Should be fine to keep it now since it's unable to pause.

**Comment by ctan-g** [comment]
@simonlingoogle Should keep the speed display, may not need the blue button. But fine to keep it

**Comment by simonlingoogle** [comment]
> @simonlingoogle Should keep the speed display, may not need the blue button. But fine to keep it

It requires some work to achieve that. 

Furthermore, I think maybe we will want to implement `pause` and `resume` (or even speed control) for log replay in the future? Thoughts? @ctan-g

**Comment by jwhui** [comment]
@simonlingoogle , please help resolve conflicts.

**Comment by simonlingoogle** [comment]
> @simonlingoogle , please help resolve conflicts.

resolved

**Pull request merged**
